### ISSUE TITLE
0.2.11 wheels include typing info

### ISSUE THREAD

**Issue by vfazio** [jquast/wcwidth#101]
While I actually appreciate this because I use typing and it allows me to drop a `#type: ignore` marker when importing the package, based on #71 not being merged, I assume they actually shouldn't be there.

The sdist does not have typing info leading me to think the wheel may have been created on a different branch?

Also, the wheel looks to have a spurious `.DS_Store` file, similar to what's mentioned here: https://github.com/pypa/wheel/issues/297

I haven't checked the CI yet, so i don't know if you're doing sdist/wheel builds and uploads there, my guess is no, but maybe they can be triggered on tags.

**Comment by GalaxySnail** [comment]
> I haven't checked the CI yet, so i don't know if you're doing sdist/wheel builds and uploads there, my guess is no, but maybe they can be triggered on tags.

You are right. Currently CI is only used for testing, sdists and wheels are built and uploaded by @jquast.

**Comment by jquast** [comment]
Sorry about that, I'll bump and make another release without it, I will be sure to `git clean` in release process, I've included a few .DS_Store's in past releases too, embarrassing !

**Comment by jquast** [comment]
0.2.12 released, thanks!
