### ISSUE TITLE
python3 package?

### ISSUE THREAD

**Issue by unsystemizer** [jquast/wcwidth#21]
I haven't tried to use wcwidth yet, but I built and installed it without issues.
With pip3 I get:

```
Collecting wcswidth
  Could not find a version that satisfies the requirement wcswidth (from versions: )
No matching distribution found for wcswidth
```

Would it be possible to create a pip3 version so that we don't have to build from source?

**Comment by jonathanslenders** [comment]
Do you have a typo there? ``wcswidth`` instead of ``wcwidth``?

**Comment by unsystemizer** [comment]
You're right, sorry. Normally I always double-check before I create issues, but while checking with pip3 I clearly made a typo and additionally I found several comments about how it'd be nice to have this for python3, so it "passed" two checks (now I looked at one of those comments again and realized it's from 2013).
