### ISSUE TITLE
Wrong width for the zero width no-break space (ZWNBSP) or byte order mark (BOM) character u+feff.

### ISSUE THREAD

**Issue by edward-dauvergne** [jquast/wcwidth#22]
Hopefully this is enough to reproduce:

```
>>> import wcwidth
>>> a = u"3\ufeff4"
>>> wcwidth.wcswidth(a)
3
>>> a
'3\ufeff4'
>>> print(a)
34
>>>
```

Rather than:

```
>>> wcwidth.wcwidth(u'\ufeff')
1
```

I would expect:

```
>>> wcwidth.wcwidth(u'\ufeff')
0
```

**Comment by jquast** [comment]
This is enough information, I hope to fix this after consulting unicode specification regarding this character.

**Comment by jquast** [comment]
This is resolved in today's release, sorry for the long turnaround
