### ISSUE TITLE
missing `wcwidth-0.1.8.tar.gz`  source archive distribution on pypi

### ISSUE THREAD

**Issue by swells** [jquast/wcwidth#31]
Please include the `tar.gz` source archive  distribution on pypi.

- Version [wcwidth-0.1.7](https://pypi.org/project/wcwidth/0.1.7/#files)  contains source archive
- Version [wcwidth-0.1.8](https://pypi.org/project/wcwidth/0.1.8/#files) does not.

Helpful for homebrew packages that depend on this lib.

**Comment by jquast** [comment]
yes of course, sorry for the oversight, the sdist is uploaded
