### ISSUE TITLE
Bad release wheel

### ISSUE THREAD

**Issue by FFY00** [jquast/wcwidth#36]
```
ERROR: wcwidth has an invalid wheel, multiple .dist-info directories found: wcwidth-0.2.0.dist-info, wcwidth-0.2.1.dist-info
```

**Comment by jquast** [comment]
Thanks, I think it's fixed, I don't know what happened, this happened when I uploaded (note the *two* pypi release pages)

```
[130][]C:\Users\jq\Code\wcwidth (master=)>twine upload dist/wcwidth-0.2.1*
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: jquast
Enter your password:
Uploading wcwidth-0.2.1-py2.py3-none-any.whl
100%|█████████████████████████████████████████████████████| 53.6k/53.6k [00:02<00:00, 19.3kB/s]
Uploading wcwidth-0.2.1.tar.gz
100%|█████████████████████████████████████████████████████| 46.0k/46.0k [00:07<00:00, 6.47kB/s]

View at:
https://pypi.org/project/wcwidth/0.2.1/
https://pypi.org/project/wcwidth/0.2.0/
```

I just bumped the version and tried again

**Comment by jquast** [comment]
I've tested it OK, thanks for the report

**Comment by FFY00** [comment]
The problem was not the upload, it was that for some reason setuptools didn't cleanup the build directory and ended up including the `.dist-info` for 0.2.0 in the 0.2.1 wheel :confused:.

**Comment by FFY00** [comment]
Anyway, I can confirm the problem is fixed. Thanks!

**Comment by mbeyeler** [comment]
Fantastic response time, @jquast!

**Comment by adamjstewart** [comment]
Should the bad release be yanked from PyPI? I just hit this same error when trying to build an older version of a package that indirectly depends on wcwidth.

**Comment by adamjstewart** [comment]
Specific error I'm seeing:
```
INFO: pip is looking at multiple versions of wcwidth to determine which version is compatible with other requirements. This could take a while.
Collecting wcwidth
  Downloading wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
  Downloading wcwidth-0.2.4-py2.py3-none-any.whl (30 kB)
  Downloading wcwidth-0.2.3-py2.py3-none-any.whl (30 kB)
  Downloading wcwidth-0.2.2-py2.py3-none-any.whl (30 kB)
  Downloading wcwidth-0.2.1-py2.py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 15.7 MB/s eta 0:00:00
ERROR: wcwidth has an invalid wheel, wcwidth has an invalid wheel, multiple .dist-info directories found: wcwidth-0.2.0.dist-info, wcwidth-0.2.1.dist-info
```
Not sure why the latest version no longer works (likely some package changed their dependencies) but if pip needs to look through multiple versions, it hits this issue.

**Comment by cweaver-logitech** [comment]
@adamjstewart I have this exact issue. I cannot for the life of me resolve it.

**Comment by adamjstewart** [comment]
@cweaver-logitech what we ended up doing was to have two files, `requirements.txt` containing all the things I care about and `constraints.txt` containing:
```
wcwidth!=0.2.1
```
Then we do:
```console
$ pip install -r requirements.txt -c constraints.txt
```
This prevents pip from using the bad wcwidth release. Would be much easier if someone could yank the release though. Hope this helps!

**Comment by cweaver-logitech** [comment]
@adamjstewart Thanks for your reply. Yeah, I would like to do that but unfortunately this package is part of a conda environment and the pip section doesn't allow much customization.

@jquast Is there any chance of kindly modifying or deleting the entry on pypi?

**Comment by adamjstewart** [comment]
For conda environments you could do something like:
```yaml
name: myenv
dependencies:
  - numpy
  - pandas
  - pip:
    - matplotlib
    - wcwidth !=0.2.1
```
It's less ideal because it will install wcwidth even if you don't need it, but it should allow your environment to resolve correctly.
