### ISSUE TITLE
change log entries missing for versions > 0.2.0

### ISSUE THREAD

**Issue by jugmac00** [jquast/wcwidth#44]
Hi,

on PyPi there is version 0.2.5 released, but in the change log the last entry is for 0.2.0.
https://github.com/jquast/wcwidth/blob/b29897e5a1b403a0e36f7fc991614981cbc42475/setup.py#L47

It would be great to add them - so I know what to expect when I update this package.

Thanks!

**Comment by jquast** [comment]
There are no API changes of any kind, feel free to browse git log to see for yourself.

I volunteer the time to document such minor changes.
