### ISSUE TITLE
Variation selectors are not correctly handled

### ISSUE THREAD

**Issue by Frederick888** [jquast/wcwidth#45]
Variation selectors (U+FE0E, U+FE0F) can change column widths of some preceding characters. For example, U+270F (✏) is a single-column glyph by itself, but with a succeeding U+FE0F it occupies 2 columns as shown in the snapshot below.

![image](https://user-images.githubusercontent.com/4507647/90748925-25221e00-e316-11ea-9c95-1b389d15e312.png)

**Comment by Frederick888** [comment]
Sorry I just went through the README. Is such kind of cases not supposed to be handled by this package?

**Comment by jquast** [comment]
This is a new one to me, yes, if iTerm and libvte-based terminals support it, then so should wcwidth! Thank you

**Comment by jquast** [comment]
I have verified that this example in particular is fixed by #91 in today's release, thank you
