### ISSUE TITLE
[document] Update some libraries which use this project

### ISSUE THREAD

**Issue by Freed-Wu** [jquast/wcwidth#66]
<https://github.com/jquast/wcwidth#uses> should contain <https://github.com/prompt-toolkit/ptpython/> because <https://github.com/prompt-toolkit/ptpython/#special-thanks-to>.

And maybe <https://github.com/executablebooks/mdformat-tables/issues/16> will use this project, too.

**Comment by jquast** [comment]
Thanks we already link to @jonathanslenders's main prompt-toolkit project, the gratitude is mutual
