### ISSUE TITLE
Upload wheel to PyPI

### ISSUE THREAD

**Issue by hugovk** [jquast/wcwidth#69]
Please could you upload a wheel for 0.2.6 and future releases?

I recommend using https://pypi.org/project/build/

```console
$ python -m pip install -U build
...
$ python -m build
...
Successfully built wcwidth-0.2.6.tar.gz and wcwidth-0.2.6-py2.py3-none-any.whl
$ ls dist
wcwidth-0.2.6-py2.py3-none-any.whl wcwidth-0.2.6.tar.gz
```

**Comment by jquast** [comment]
Yes, of course. I’ll look into it.

I did use “build” package, following the latest available instructions for publishing wheels, no idea what went wrong. Seems every year there is a new tool or technique for publishing to pypi, I’m have a hard time keeping up! I don’t understand why there is a need for so many third party tools and documentation.

**Comment by maxwell-k** [comment]
Thank you for the wheel upload, that is brilliant!  I appreciate your time.

In case it is any comfort, in my personal opinion the time frame for this release — 2020 - 2023 — has seen a lot of change in the Python packaging universe, I expect that the time frame for the your release will be quieter.
